### ISSUE TITLE
Promise-based functions should not throw exceptions

### ISSUE THREAD

**Issue by amer8** [wallee-payment/typescript-sdk#1]
https://2ality.com/2016/03/promise-rejections-vs-exceptions.html

How to reproduce:
- Void a completed transaction 
- Transaction not in the correct state
- Server responds with developer_error
- .voidOnline() throws err internally, server crashes.

How to fix:
- Instead of throwing err, the Promise function should reject(err) regardless of the err type.

**Comment by vttn** [comment]
Fixed in 2.0.3
