### ISSUE TITLE
Double declaration of spaceId

### ISSUE THREAD

**Issue by amer8** [wallee-payment/typescript-sdk#3]
The question is whether `spaceId` can be omitted from the config object.
It seems that it's being sent later, when using the service methods `transactionService.create(spaceId, transaction)`.

In this case `api_secret` belongs to `user_id` and the SDK could send requests to different spaces the user belongs to, by choosing the spaceId on every method.

**Comment by vttn** [comment]
Hello @amer8 

You are correct in assuming that a user with a given secret can have multiple spaces.

You can omit the space_id from the config if you like.

```
// config
let space_id: number = 321
let config: {user_id: number, api_secret: string } = {
    user_id: 123,
    api_secret: 'abc'
};
```

Victor
